build-and-deploy:
    tags:
      - shell-runner-docker-8001
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
          when: always
        - when: never
    script:
        - docker rm -f tgb
        - docker tag tgb:latest tgb:old
        - docker build -t tgb:latest ${CI_PROJECT_DIR}
        - docker run -v $MANICTIME_JSON_FILE_PATH:$MANICTIME_JSON_FILE_PATH -e TELEGRAM_BOT_API_KEY=$TELEGRAM_BOT_API_KEY -d --restart unless-stopped --name tgb tgb:latest
        - echo all done docker container made
        - docker ps -a

build-and-deploy-test:
    tags:
      - shell-runner-docker-8001
    rules:
        - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
          when: manual
        - when: never
    script:
        - docker rm -f tgb-test || echo tried to remove test-contailer but failed
        - docker rmi tgb-test:latest || echo tried to remove test-image but failed
        - docker build -t tgb-test:latest ${CI_PROJECT_DIR}
        - docker run -v $MANICTIME_JSON_FILE_PATH:$MANICTIME_JSON_FILE_PATH -e TELEGRAM_BOT_API_KEY=$TELEGRAM_TEST_BOT_API_KEY -d --restart unless-stopped --name tgb-test tgb-test:latest


stop-test-job:
    tags:
      - shell-runner-docker-8001
    rules:
        - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
          when: manual
        - when: never
    script:
        - docker rm -f tgb-test || echo tried to remove test-contailer but failed

SonarQube-check:
  when: manual
  image: 
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - sonar-scanner
  allow_failure: true
  tags:
    - docker
