workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE != "merge_request_event"'

run-tests:
  script:
    - docker build -t test:tgbtest .

build-and-deploy:
    tags:
      - shell-runner-docker-8001
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
          when: always
        - when: never
    script:
        - docker rm -f tgb
        - docker build -t tgb:latest ${CI_PROJECT_DIR}
        - docker run -h tgb-prod-container -v $MANICTIME_JSON_FILE_PATH:$MANICTIME_JSON_FILE_PATH -e TELEGRAM_BOT_API_KEY=$TELEGRAM_BOT_API_KEY -e PRODUCTION=1 -d --restart unless-stopped --name tgb tgb:latest
        - echo all done docker container made
        - docker ps -a

build-and-deploy-test:
    tags:
      - shell-runner-docker-8001
    rules:
        - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
          when: always
        - when: never
    script:
        - docker rm -f tgb-test || echo tried to remove test-contailer but failed
        - docker rmi tgb-test:latest || echo tried to remove test-image but failed
        - docker build -t tgb-test:latest ${CI_PROJECT_DIR}
        - docker run -v $MANICTIME_JSON_FILE_PATH:$MANICTIME_JSON_FILE_PATH -e TELEGRAM_BOT_API_KEY=$TELEGRAM_TEST_BOT_API_KEY -d --restart unless-stopped --name tgb-test tgb-test:latest


stop-test-job:
  timeout: 15m 
  tags:
    - shell-runner-docker-8001
  script:
    - docker rm -f tgb-test || echo tried to remove test-contailer but failed
  rules:
    - if: "$CI_COMMIT_BRANCH!=$CI_DEFAULT_BRANCH"
      when: manual
    - when: always

