
the_activities_markup = [
	'/key ci, 600',
	'/key ci, 1200',
	'/key ci, 20',
	'/now reading',
	'/now job',
	'/now writing',
	'/now cleaning',
	'/now walking',
	'/now exercise',
	'/now driving',
	'/now uber',
	'/now programming',
	'/now linux',
	'/now doing phone',
	'/now goal setting',
	"/now sleep",
	"/now eye candy",
	"/now food",
	'/now Trying or setting up',
	'/now other people',
	'/now plantme',
	'/now udemy',
	'/top 24',
	'/top 24*7',
	'/top 24*30',
	'/top 24*90',
	'/now bio',
	'/now manictime',
	'/now thinking',
	'/now family',
	'/now ecl',
	'/now YouTube',
	'/now shopping',
	'/now data',
	'/now money',
	'/now sick',



]
