# Generated by Django 5.1.15 on 2026-07-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, default=1040271347)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('source', models.CharField(default='telegram', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['user_id', 'start_time', 'end_time'], name='tracker_act_user_id_56630f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, default=1040271347)),
                ('category_name', models.CharField(db_index=True, max_length=255)),
                ('period', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], default='day', max_length=20)),
                ('goal_type', models.CharField(choices=[('at_least', 'At Least'), ('at_most', 'At Most'), ('range', 'Range')], default='at_least', max_length=20)),
                ('target_min_seconds', models.IntegerField(default=0)),
                ('target_max_seconds', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('user_id', 'category_name', 'period')},
            },
        ),
        migrations.CreateModel(
            name='KeyValuePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, default=1040271347)),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('value', models.TextField(blank=True, default='')),
            ],
            options={
                'unique_together': {('user_id', 'key')},
            },
        ),
    ]
