name: CI deploy
on: 
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          if_key_exists: "ignore" 
          key: ${{ secrets.OMG_secret }}
          known_hosts: 'placeholder' #https://zellwk.com/blog/github-actions-deploy/
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      - name: copy all
        run: scp -r ./* ls@${{secrets.HOST}}:/home/ls/tg/
      - name: build new image
        run: ssh ls@${{secrets.HOST}} newgrp docker && docker build -t lak.nz/tgb:local /home/ls/tg
      - name: remove old container
        run: ssh ls@${{secrets.HOST}} docker rm -f tgb
      - name: init a new container
        run: "docker run -d -v /keyval.db:/app/keyval.db --name tgb lak.nz/tgb:local"
