name: Google CI deploy
on: 
  push:
    branches: [main]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          if_key_exists: "ignore" 
          key: ${{ secrets.OMG_secret }}
          known_hosts: 'placeholder' #https://zellwk.com/blog/github-actions-deploy/
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      - name: copy all
        run: |
              pwd
              ssh ls@${{secrets.HOST}} pwd
      - name: restart service
        run: |              
              ssh ls@${{secrets.HOST}} echo "hello2"