name: learn-github-actions
on: 
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: laksh
          key: ${{ secrets.OMG_secret }}
          port: 22
          script: |
            cd tg/
            git status
